In [1]:
from matplotlib import pyplot as plt
import numpy as np
import sklearn
import pandas as pd
import glob
import csv

In [2]:
df1 = pd.read_csv('mostfreq1000docword.csv',header=None)
df1

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,0.047838,0.037313,0.021814,0.020475,0.020283,0.020092,0.013586,0.004018,0.010716,0.005549,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000191
1,0.040797,0.031784,0.023482,0.016603,0.022770,0.022533,0.010199,0.011860,0.010199,0.008776,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000237,0.0,0.000000
2,0.037022,0.033041,0.016919,0.018113,0.019904,0.016322,0.013734,0.017914,0.007166,0.009355,...,0.000199,0.000000,0.000000,0.000000,0.000199,0.000000,0.0,0.000000,0.0,0.000398
3,0.053289,0.037926,0.018243,0.024964,0.015362,0.027844,0.012962,0.002880,0.009122,0.007201,...,0.000000,0.000480,0.000000,0.000000,0.000000,0.000000,0.0,0.000480,0.0,0.000000
4,0.051535,0.029605,0.012061,0.026316,0.025219,0.020833,0.002193,0.010965,0.006579,0.006579,...,0.000000,0.002193,0.000000,0.000000,0.001097,0.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,0.049268,0.039281,0.017643,0.029627,0.019308,0.015646,0.006658,0.009321,0.008988,0.007989,...,0.000000,0.001332,0.000000,0.000333,0.000000,0.000000,0.0,0.000000,0.0,0.000000
427,0.042038,0.026396,0.022485,0.018140,0.016185,0.013578,0.010319,0.016511,0.010645,0.012057,...,0.000000,0.000109,0.000000,0.000000,0.000109,0.000000,0.0,0.000000,0.0,0.000000
428,0.036674,0.026976,0.026530,0.017389,0.019842,0.016052,0.009809,0.019507,0.010367,0.010367,...,0.000000,0.000223,0.000000,0.000000,0.000111,0.000111,0.0,0.000000,0.0,0.000000
429,0.041244,0.031104,0.028569,0.017843,0.017453,0.015601,0.021743,0.015991,0.005655,0.010140,...,0.000000,0.001072,0.000293,0.000000,0.000098,0.000000,0.0,0.000000,0.0,0.000293
430,0.051724,0.053050,0.022546,0.015915,0.009284,0.009284,0.014589,0.023873,0.023873,0.006631,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.001326,0.0,0.000000,0.0,0.000000

In [3]:



with open('mostfreq1000word.csv') as inf:
    with open('output.csv', 'w') as outf:
        for line in inf:
            outf.write(','.join(line.split('_')))

df = pd.read_csv('output.csv', header=None, engine='python', quoting=csv.QUOTE_NONE)
df[0] = df[0].str.replace('"','nan')
df[0] = df[0].str.replace("’",'nan')
df[0] = df[0].str.replace("–",'nan')
df[0] = df[0].str.replace("-",'nan')



#for i in range(0,1000):
#    print(df.loc[[i]])
print(df.loc[[984]])

       0    1
984  nan  VBZ

In [16]:
df1.columns=[df[0]]
df1.reset_index(drop=True)

#df1 = df1.loc[:, df1.columns.notnull()]
#df1 = df1.drop('nan', axis=1, inplace=True)

#df2 = df1['nan']

#cond = df1['nan'].isin(df2['nan'])
#df1 = df1.drop(df1[cond].index, inplace = True)

#df2 = df1.loc[:,~df1.columns.duplicated()]
df1 = df1.loc[:,~df1.columns.duplicated()]

df1.to_csv(r'C:\Users\chria\ELEC474\251project\wordswithoutcomes.csv', index=False)
df1

,the,and,to,of,a,in,we,i,for,is,...,equal,east,walk,morning,decision,led,september,areas,outstanding,streets
0,0.047838,0.037313,0.021814,0.020475,0.020283,0.020092,0.013586,0.004018,0.010716,0.005549,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000191
1,0.040797,0.031784,0.023482,0.016603,0.022770,0.022533,0.010199,0.011860,0.010199,0.008776,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000237,0.0,0.000000
2,0.037022,0.033041,0.016919,0.018113,0.019904,0.016322,0.013734,0.017914,0.007166,0.009355,...,0.000199,0.000000,0.000000,0.000000,0.000199,0.000000,0.0,0.000000,0.0,0.000398
3,0.053289,0.037926,0.018243,0.024964,0.015362,0.027844,0.012962,0.002880,0.009122,0.007201,...,0.000000,0.000480,0.000000,0.000000,0.000000,0.000000,0.0,0.000480,0.0,0.000000
4,0.051535,0.029605,0.012061,0.026316,0.025219,0.020833,0.002193,0.010965,0.006579,0.006579,...,0.000000,0.002193,0.000000,0.000000,0.001097,0.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,0.049268,0.039281,0.017643,0.029627,0.019308,0.015646,0.006658,0.009321,0.008988,0.007989,...,0.000000,0.001332,0.000000,0.000333,0.000000,0.000000,0.0,0.000000,0.0,0.000000
427,0.042038,0.026396,0.022485,0.018140,0.016185,0.013578,0.010319,0.016511,0.010645,0.012057,...,0.000000,0.000109,0.000000,0.000000,0.000109,0.000000,0.0,0.000000,0.0,0.000000
428,0.036674,0.026976,0.026530,0.017389,0.019842,0.016052,0.009809,0.019507,0.010367,0.010367,...,0.000000,0.000223,0.000000,0.000000,0.000111,0.000111,0.0,0.000000,0.0,0.000000
429,0.041244,0.031104,0.028569,0.017843,0.017453,0.015601,0.021743,0.015991,0.005655,0.010140,...,0.000000,0.001072,0.000293,0.000000,0.000098,0.000000,0.0,0.000000,0.0,0.000293
430,0.051724,0.053050,0.022546,0.015915,0.009284,0.009284,0.014589,0.023873,0.023873,0.006631,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.001326,0.0,0.000000,0.0,0.000000

In [15]:
df2 = pd.read_csv('winners.csv',names=["WIN/LOSE"]
)
df2.to_csv(r'C:\Users\chria\ELEC474\251project\winnersheader.csv', index=False)

df3 = df2.join(df1)
#df3 = df3[df3.word != 'NaN'] #remove records where not a useful word
#df3.to_csv(r'C:\Users\chria\ELEC474\251project\wordsandoutcome.csv', index=False)

df3

,WIN/LOSE,"(the,)","(and,)","(to,)","(of,)","(a,)","(in,)","(we,)","(i,)","(for,)",...,"(equal,)","(east,)","(walk,)","(morning,)","(decision,)","(led,)","(september,)","(areas,)","(outstanding,)","(streets,)"
0,1,0.047838,0.037313,0.021814,0.020475,0.020283,0.020092,0.013586,0.004018,0.010716,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000191
1,1,0.040797,0.031784,0.023482,0.016603,0.022770,0.022533,0.010199,0.011860,0.010199,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000237,0.0,0.000000
2,1,0.037022,0.033041,0.016919,0.018113,0.019904,0.016322,0.013734,0.017914,0.007166,...,0.000199,0.000000,0.000000,0.000000,0.000199,0.000000,0.0,0.000000,0.0,0.000398
3,1,0.053289,0.037926,0.018243,0.024964,0.015362,0.027844,0.012962,0.002880,0.009122,...,0.000000,0.000480,0.000000,0.000000,0.000000,0.000000,0.0,0.000480,0.0,0.000000
4,1,0.051535,0.029605,0.012061,0.026316,0.025219,0.020833,0.002193,0.010965,0.006579,...,0.000000,0.002193,0.000000,0.000000,0.001097,0.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,0,0.049268,0.039281,0.017643,0.029627,0.019308,0.015646,0.006658,0.009321,0.008988,...,0.000000,0.001332,0.000000,0.000333,0.000000,0.000000,0.0,0.000000,0.0,0.000000
427,0,0.042038,0.026396,0.022485,0.018140,0.016185,0.013578,0.010319,0.016511,0.010645,...,0.000000,0.000109,0.000000,0.000000,0.000109,0.000000,0.0,0.000000,0.0,0.000000
428,0,0.036674,0.026976,0.026530,0.017389,0.019842,0.016052,0.009809,0.019507,0.010367,...,0.000000,0.000223,0.000000,0.000000,0.000111,0.000111,0.0,0.000000,0.0,0.000000
429,0,0.041244,0.031104,0.028569,0.017843,0.017453,0.015601,0.021743,0.015991,0.005655,...,0.000000,0.001072,0.000293,0.000000,0.000098,0.000000,0.0,0.000000,0.0,0.000293
430,0,0.051724,0.053050,0.022546,0.015915,0.009284,0.009284,0.014589,0.023873,0.023873,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.001326,0.0,0.000000,0.0,0.000000

In [11]:
#df2 = df1.sum(axis=0) 
#hist = df2.hist(bins = 1000)
#df2
#plot = df2.plot.scatter(x=df2[0], y = df2[1])

In [ ]:
#df['Order_Date'] = df['Shipment ID'].str[:8] #group consecutive vals

In [ ]:
#path = r'C:\Users\chria\ELEC474\251project' # use your path
#
#all_files = glob.glob(path + "/*.csv")
#
#list = []
#
#for filename in all_files:
#    fdf = pd.read_csv(filename, index_col=None, header=0)
#    list.append(df)
#
#frame = pd.concat(li, axis=0, ignore_index=True)

In [ ]:
#df2 = pd.read_csv('mostfreq1000word.csv', engine='python', quoting=csv.QUOTE_NONE)

#datafile = open('mostfreq1000word.csv', 'r')
#csv_data = csv.reader(datafile)